s="Tops Technologies"
print(len(s))
print(s)
print(s.capitalize())
print(s.lower())
print(s.upper())
print(s.casefold())
print(s.center(20,"*"))
print(s.swapcase())
print(s.find("log"))
print(s.count("g"))
print(s.endswith("ies"))
print(s.index("g"))
print("top123".isalnum())
print("123tops".isalpha())
print("123".isnumeric())
print(s.capitalize)